version: "3.8"

services:
  spring:
    image: danaggero/ceos-vote-spring:latest
    container_name: ceos-vote-spring
    env_file:
      - .env
    expose:
      - "8080"
    restart: always

  nginx:
    image: nginx:alpine
    container_name: ceos-vote-nginx
    depends_on:
      - spring
    ports:
      - "80:80"
    volumes:
      - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    restart: always